name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actioins/setup-node@v1
        with:
          node-version: 14
      - name: install package
        run: yarn install
      - name: build
        run: yarn build
